### ISSUE TITLE
date_num Function Day Method Failure

### ISSUE THREAD

**Issue by brichard1638** [ShichenXie/xefun#1]
The xefun is a great R package! However, a recent addition made to the package in the form of the date_num function does not work as intended. When the origin date is modified, the results are still computed based on the original origin date. To replicate the issue for a day configuration, apply the following code:

>library(xefun)
date_num("2022-02-01", unit = 'd', origin = "2022-01-01")
[1] "19024"

The correct value should be 31. A modification below resolves the issue for all units of configuration (milliseconds, seconds, and days). I have improved functionality by integrating additional units of configuration into the function to include minutes, hours, and weeks. I also modified the default unit of configuration from seconds to days:

>datenum = function (x, unit = "d", origin = "1970-01-01") 
{
  unit = match.arg(unit, c("ms", "s", "m", "h", "d", "w"))
  if (unit == "ms") {
    xnum = format(difftime(x, origin, units = "secs"), trim = TRUE, scientific = FALSE)
    xnum = easyr::left(xnum, nchar(xnum)-5)
    xnum = as.numeric(xnum)*1000
  }
  else if (unit == "s") {
    xnum = format(difftime(x, origin, units = "secs"), trim = TRUE, scientific = FALSE)
    xnum = easyr::left(xnum, nchar(xnum)-5)
  }
  else if (unit == "m") {
    xnum = format(difftime(x, origin, units = "mins"), trim = TRUE, scientific = FALSE)
    xnum = easyr::left(xnum, nchar(xnum)-5)
  }
  else if (unit == "h") {
    xnum = format(difftime(x, origin, units = "hours"), trim = TRUE, scientific = FALSE)
    xnum = easyr::left(xnum, nchar(xnum)-6)
  }  
  else if (unit == "d") {
    xnum = format(difftime(x, origin, units = "days"), trim = TRUE, scientific = FALSE)
    xnum = easyr::left(xnum, nchar(xnum)-5)
  }
  else if (unit == "w") {
    xnum = format(difftime(x, origin, units = "weeks"), trim = TRUE, scientific = FALSE)
    xnum = easyr::left(xnum, nchar(xnum)-7)
  }
  return(format(xnum, scientific = FALSE))
}
-------------------------------
For the DAY configuration, the function now works as intended:
>datenum(x = "2022-02-01", origin = "2022-01-01")
[1] "31"

To make the dates inclusive, use the following code which can be added either within the function itself, or as an independent computation of the datefun function. Another possible option is to add an argument for the days unit of configuration allowing the user to configure whether or not the days are inclusive or not:
>as.numeric(datenum(x = "2022-12-25", unit = "d", origin = "2022-12-01"))+1
[1] 25

For SECONDS and MILLISECONDS:
>datenum(x = "2022-12-25", unit = "s", origin = "2022-12-24")
[1] "86400"

>datenum(x = "2022-12-25", unit = "ms", origin = "2022-12-24")
[1] "86400000"

For the WEEK unit of configuration:
>datenum(x = "2022-12-25", unit = "w", origin = "2022-12-01")
[1] "3.42857"

OTHER CONSIDERATIONS:
- How NAs are handled within a vector - this issue is not addressed in the proposed code solution.
- "m" as a unit argument may be confusing to the user as it could be interpreted as either minutes or months. The "m" argument was used but it may reduce the uncertainty to change this argument value from "m" to "min." It is also possible that "ms" could be misconstrued. A better unit definition for millisecond would be "mil."
- Rounding can be controlled either independent of the function, hard coded as a configuration, or as an added argument.
- Determine whether to add date inclusion to the function. The example above addresses the issue relative to the day unit of configuration. However, inclusion can be applied to all units of configuration depending on whether to include the start date or not.
- While expanding the date_num function will add a dependency to the xefun package, it is believed to be worth the inconvenience trading a mild increase in complexity for additional functionality.

It should be noted that the modifications made to the function do not impact its scope utility. The function works with both scalers and vectors.

One more comment relative to this function: As proposed, it would be a functional improvement to add minutes, hours, and weeks as additional unit possibilities.

**Comment by ShichenXie** [comment]
Thanks. I have modified the date_num function based on your suggestions (e4ee30a9f952e334eb91f38d77d37378c466a490).
